name: rosbot
adopt-info: rosbot
license: Apache-2.0
summary: The rosbot
description: |
  The rosbot snap contains all the necessary software to bring the robot up
  such as controller, robot state publisher etc.

  It offers the following parameters,

    - mecanum
    - serial-port
    - serial-baudrate
    - namespace

  which can be set as follows, e.g.,

    snap set rosbot mecanum=True

grade: stable
confinement: strict
base: core22

contact: https://github.com/husarion/rosbot-snap/issues
issues: https://github.com/husarion/rosbot-snap/issues
website: https://husarion.com/

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

apps:
  rosbot:
    command: usr/bin/launcher.sh
    daemon: simple
    install-mode: disable
    plugs: 
      - network
      - network-bind
      - serial-port
    extensions:
      - ros2-humble-ros-base

parts:
  rosbot:
    plugin: colcon
    source: https://github.com/husarion/rosbot_ros.git
    build-packages: 
      - python3-vcstool
    stage-packages: 
      - stm32flash
    override-pull: |

      craftctl default

      vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/rosbot/rosbot_hardware.repos
      # we don't want to build all controllers
      cp -r $CRAFT_PART_SRC/ros2_controllers/diff_drive_controller $CRAFT_PART_SRC/
      cp -r $CRAFT_PART_SRC/ros2_controllers/imu_sensor_broadcaster $CRAFT_PART_SRC/
      rm -rf $CRAFT_PART_SRC/ros2_controllers
      # it is necessary to remove simulation - otherwise rosdep tries to install dependencies
      # rm -r $CRAFT_PART_SRC/rosbot_gazebo

      # Ignore so that rosdep doesn't pull deps
      # and colcon doesn't build
      touch $CRAFT_PART_SRC/rosbot_gazebo/COLCON_IGNORE

      # Set the snap version from the git tag
      # The grade is set to 'stable' if the latest entry in the git history
      # is the tag itself, otherwise set to devel
      version="$(git describe --always --tags| sed -e 's/^v//;s/-/+git/;y/-/./')"
      [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
      craftctl set version="$version"
      craftctl set grade="$grade"

  # copy local scripts to the snap usr/bin
  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
