#!/bin/sh -e

# Parameters are 'unset'.
# Default configuration values is left to the launch file.
snapctl set mecanum=True
snapctl set serial-port=${SERIAL_PORT:-/dev/ttySERIAL} 
snapctl set serial-baudrate=576000
# snapctl set namespace=${ROBOT_NAMESPACE:-robot}

if ! snapctl is-connected ros-humble; then
  logger -t ${SNAP_NAME} "Plug 'ros-humble' isn't connected, \
    please run: snap connect ${SNAP_NAME}:ros-humble <providing-snap>"
fi
